# Generated by Django 2.2 on 2021-12-15 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ToDoApp', '0002_auto_20211215_1125'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='id',
            new_name='uid',
        ),
    ]
