# Generated by Django 2.2 on 2021-11-30 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memoryApp', '0003_auto_20211130_0206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memory',
            name='dateOfOccurence',
            field=models.DateTimeField(null=True, verbose_name='date of occurence'),
        ),
    ]
