# Generated by Django 2.2 on 2021-11-30 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memoryApp', '0004_auto_20211130_0207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memory',
            name='dateOfOccurence',
            field=models.DateField(null=True, verbose_name='date of occurence'),
        ),
    ]
