# Generated by Django 2.2 on 2021-12-02 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memoryApp', '0008_auto_20211202_1604'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='memory',
            options={'verbose_name': 'Memory', 'verbose_name_plural': 'Memories'},
        ),
    ]
